package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/MicahParks/keyfunc"
	jwt "github.com/golang-jwt/jwt/v4"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
)

type TokenExchange struct {
	AccessToken      string `json:"access_token"`
	ExpiresIn        int    `json:"expires_in"`
	RefreshExpiresIn int    `json:"refresh_expires_in"`
	NotBeforePolicy  int    `json:"not-before-policy"`
	IssuedTokenType  string `json:"issued_token_type"`
	AccountLinkURL   string `json:"account-link-url"`
}

type KeycloakToken struct {
	SessionState   string   `json:"session_state"`
	Acr            string   `json:"acr"`
	AllowedOrigins []string `json:"allowed-origins"`
	RealmAccess    struct {
		Roles []string `json:"roles"`
	} `json:"realm_access"`
	ResourceAccess struct {
		RealmManagement struct {
			Roles []string `json:"roles"`
		} `json:"realm-management"`
		Broker struct {
			Roles []string `json:"roles"`
		} `json:"broker"`
		Account struct {
			Roles []string `json:"roles"`
		} `json:"account"`
	} `json:"resource_access"`
	Scope             string   `json:"scope"`
	Sid               string   `json:"sid"`
	EmailVerified     bool     `json:"email_verified"`
	Name              string   `json:"name"`
	Groups            []string `json:"groups"`
	PreferredUsername string   `json:"preferred_username"`
	GivenName         string   `json:"given_name"`
	FamilyName        string   `json:"family_name"`
	Email             string   `json:"email"`
	jwt.RegisteredClaims
}

var (
	jwks      *keyfunc.JWKS
	clientset *kubernetes.Clientset
)

func init() {
	jwksURL := os.Getenv("KEYCLOAK_CERT_URL")

	options := keyfunc.Options{
		RefreshErrorHandler: func(err error) {
			log.Printf("There was an error with the jwt.Keyfunc\nError: %s", err.Error())
		},
		RefreshInterval:   time.Hour,
		RefreshRateLimit:  time.Minute * 5,
		RefreshTimeout:    time.Second * 10,
		RefreshUnknownKID: true,
	}

	// Create the JWKS from the resource at the given URL.
	err := error(nil)
	jwks, err = keyfunc.Get(jwksURL, options)
	if err != nil {
		log.Fatalf("Failed to create JWKS from resource at the given URL.\nError: %s", err.Error())
	}

	if os.Getenv("DEV") == "true" {
		var kubeconfig *string
		if home := homedir.HomeDir(); home != "" {
			kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
		} else {
			kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
		}
		flag.Parse()

		config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
		if err != nil {
			panic(err)
		}
		clientset, err = kubernetes.NewForConfig(config)
		if err != nil {
			panic(err)
		}
	} else {
		// creates the in-cluster config
		config, err := rest.InClusterConfig()
		if err != nil {
			panic(err.Error())
		}
		// creates the clientset
		clientset, err = kubernetes.NewForConfig(config)
		if err != nil {
			panic(err.Error())
		}
	}
}

func fatal(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	// define origin server URLs
	originServerURL, err := url.Parse(os.Getenv("UPSTREAM_URL"))
	originBypassServerURL, err := url.Parse(os.Getenv("UPSTREAM_BYPASS_URL"))
	AccessToken := os.Getenv("ACCESSTOKEN")
	fatal(err)
	reverseProxy := http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		fmt.Printf("[reverse proxy server] received request at: %s\n", time.Now())

		//parse jwt from request
		var keycloakToken KeycloakToken
		token, err := jwt.ParseWithClaims(req.Header.Get("Authorization"), &keycloakToken, jwks.Keyfunc)
		//if token invalid or expired, return 401
		if !token.Valid {
			rw.WriteHeader(http.StatusForbidden)
			_, _ = fmt.Fprint(rw, err)
			return
		}

		//if user in admin group
		if keycloakToken.Groups[0] == os.Getenv("ADMIN_GROUP") && strings.ToLower(os.Getenv("TOKEN_EXCHANGE")) == "true" {

			// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
			params := url.Values{}
			params.Add("client_id", `grafana`)
			params.Add("client_secret", os.Getenv("CLIENT_SECRET"))
			params.Add("subject_token", req.Header.Get("Authorization"))
			params.Add("requested_issuer", `openshift`)
			params.Add("grant_type", `urn:ietf:params:oauth:grant-type:token-exchange`)
			params.Add("audience", `grafana`)
			body := strings.NewReader(params.Encode())

			tokenExchangeRequest, err := http.NewRequest("POST", "https://sso.apps.play.gepaplexx.com/realms/internal/protocol/openid-connect/token", body)
			fatal(err)
			tokenExchangeRequest.Header.Set("Content-Type", "application/x-www-form-urlencoded")

			resp, err := http.DefaultClient.Do(tokenExchangeRequest)
			fatal(err)
			defer resp.Body.Close()
			b, err := io.ReadAll(resp.Body)
			fatal(err)

			var result TokenExchange
			err = json.Unmarshal(b, &result)
			fatal(err)
			//request to bypass origin server
			req.Host = originBypassServerURL.Host
			req.URL.Host = originBypassServerURL.Host
			req.URL.Scheme = originBypassServerURL.Scheme
			req.Header.Set("Authorization", "Bearer "+result.AccessToken)

		} else {
			rolebindings, err := clientset.RbacV1().RoleBindings("").List(context.TODO(), metav1.ListOptions{
				FieldSelector: "metadata.name=gp-dev",
			})
			var namespaces []string
			for _, rb := range rolebindings.Items {
				for _, user := range rb.Subjects {
					if fmt.Sprintf("%s", user.Name) == keycloakToken.PreferredUsername {
						namespaces = append(namespaces, rb.Namespace)
					}
				}
			}
			// save the response from the origin server
			URL := req.URL.String()
			quIn := strings.Index(URL, "query?") + 6
			req.URL, err = url.Parse(URL[:quIn] + "namespace=" + strings.Join(namespaces[:], "|") + "&" + URL[quIn:])
			fatal(err)

			//proxy request to origin server
			req.Host = originServerURL.Host
			req.URL.Host = originServerURL.Host
			req.URL.Scheme = originServerURL.Scheme
			req.Header.Set("Authorization", "Bearer "+AccessToken)
		}

		//clear request URI
		req.RequestURI = ""
		originServerResponse, err := http.DefaultClient.Do(req)
		if err != nil {
			rw.WriteHeader(http.StatusInternalServerError)
			_, _ = fmt.Fprint(rw, err)
			return
		}

		// return response to the client
		rw.WriteHeader(http.StatusOK)
		io.Copy(rw, originServerResponse.Body)
	})

	log.Fatal(http.ListenAndServe(":8080", reverseProxy))
}
